#!/usr/bin/env bash

# This hook check if the branch to commit is a issue number and, if it is, prepend a fixed string
develop_branch="develop"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

branchname_regex='^[0-9]+$'
error_msg="Aborting commit. Your develop's children branch must be a jira issue number"
if ! grep -iqE "$branchname_regex" <<< "$current_branch"; then
    echo "$error_msg" >&2
    exit 1
fi

commitmsg_regex='^\s*#NPS-[0-9]+'
msg=`cat "$1"`
echo "test"
if ! grep -iqE "$commitmsg_regex" <<< "$msg"; then
    echo "#NPS-$current_branch: $msg" > "$1"
fi
exit 0

# This hook manage commit message only if it is in the branch develop
#current_branch="$(git rev-parse --abbrev-ref HEAD)"
#
#error_msg="Aborting commit. You can commit only on develop branch"
#if [ ! "develop" == "$current_branch" ] ; then
#    echo "$error_msg" >&2
#    exit 1
#fi
#
#commitmsg_regex='^\s*#NPS-[0-9]+'
#if ! grep -iqE "$commitmsg_regex" <<< "$1"; then
#    echo "#NPS-$current_branch: $1" > "$1"
#fi
#exit 0
