#!/usr/bin/env bash

develop_branch="develop"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

branchname_regex='#NPS-[0-9]+'
error_msg="Aborting commit. Your develop's children branch must start with 'NPS-nnn'"
if ! grep -iqE "$branchname_regex" "$current_branch"; then
    echo "$error_msg" >&2
    exit 1
fi

description="`cat $1`"
echo "$current_branch: $description" > "$1"
