#!/usr/bin/env bash
# This hook check if the branch is formed by a issue number and, optionally, a string with underscore

current_branch_name="$(git rev-parse --abbrev-ref HEAD)"
previous_branch_name="$(git rev-parse --symbolic @{-1})"
branch_name_regex='^[0-9]+|[0-9]+-[a-zA-Z_]+|master|develop$'

if ! grep -iqE "$branch_name_regex" <<< "$current_branch_name" ; then   
    error_msg="Aborting checkout. The branch to checkout must begin with a issue number followed by an optional minus and an optional description"
    echo "$error_msg" >&2
    exec git checkout -q "$previous_branch_name"
    exit 1
fi

exit 0
