set -xg PATH $PATH:~/.local/bin:~/.nexustools
set -xg TERM screen-256color
set -xg CLICOLOR 1
set -xg CLICOLOR_FORCE 1
set -xg LSCOLOR Gxfxcxdxbxegedabagacad
set -xg GREP_OPTIONS '--color=auto'
set -xg GREP_COLOR '3;33'
set -xg JEKYLL_GITHUB_TOKEN 'c5826f89fba802f901cb846fbaf5e3f3059e51af'
set -xg EDITOR nvim
set -xg DOCKERFILES "$DOTFILES/dockerFiles/"
